name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - run: echo $RUNNER_TOOL_CACHE
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  mac:
    runs-on: macos-latest
    steps:
    - run: echo $RUNNER_TOOL_CACHE
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  win:
    runs-on: windows-latest
    steps:
    - run: echo %RUNNER_TOOL_CACHE%
    - run: ls $RUNNER_TOOL_CACHE/Python
      shell: bash
    - run: ls $RUNNER_TOOL_CACHE/PyPy
      shell: bash

  python381:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python${{ matrix.python-version }} \
          python${{ matrix.python-version }}-dev python3-pip build-essential
      - name: Show Python version
        run: python${{ matrix.python-version }} --version
