name: Check PR for WIP and Blocked labels
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const is_blocked_label = (label) => label.name.startsWith('Blocked') || label.name == 'Work In Progress';
            console.log(context.payload.pull_request.labels);
            console.log(context)
            console.log(context.pull_request)
            console.log(context.payload.pull_request)
            if (context.payload.pull_request.labels.some(is_status_label)) {
                const status = 'pending';
            } else {
                const status = 'success';
            }
            github.checks.create({
              name: 'No WIP and Blocked labels',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.pull_request.head.sha,
              status: status
            });
