name: Check PR for WIP and Blocked labels
on:
  pull_request:
    types: [labeled, unlabeled, synchronized]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Install action's requirements"
        run: npm install
        working-directory: ./.github/actions/check_wip_and_blocked_labels
      - name: Check PR for WIP and Blocked labels
        uses: ./.github/actions/check_wip_and_blocked_labels
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
