name: Check PR for WIP and Blocked labels
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check_wip_and_blocked_labels
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
