name: Check PR for WIP and Blocked labels
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const core = require('@actions/core');
            const is_blocked_label = (label) => label.name.startsWith('Blocked') || label.name == 'Work In Progress';
            console.log(context.payload.pull_request.labels);
            console.log(context)
            console.log(context.pull_request)
            console.log(context.payload.pull_request)
            if (context.payload.pull_request.labels.some(is_blocked_label)) {
                core.setFailed('PR has a Blocked/WIP label. DO NOT MERGE.');
                const status = 'pending';
            } else {
                const status = 'success';
            }
