on:
  push:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables.
        run: |
          printenv

      - name: Install heroku-cli.
        run: |
          sudo snap install heroku --classic

      - name: Setup tmate session
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
