name: Host SSH session.
on:
  workflow_dispatch:

jobs:
  ngrok:
    environment: Ngrok
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@v1.0
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
