name: Host SSH session.
run-name: "Host SSH session (${{ github.event.inputs.runs-on }})"
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'OS to run on.'
        type: choice
        options:
          # Ubuntu
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-slim
          # macoOS
          - macos-15-intel
          - macos-latest
          - macos-15
          - macos-14
          # Windows
          - windows-latest
          - windows-2025
          - windows-2022
          - windows-11-arm
        default: ubuntu-latest

jobs:
  ngrok:
    environment: Ngrok
    runs-on: "${{ github.event.inputs.runs-on }}"
    steps:
      - name: blah
        run: |
          winget install "openssh preview"

      - name: Start SSH session
        uses: Jackenmen/debug-via-ssh@5bc95bd79654dd1fe9cfa1bcd7d39d69a9fecc44
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
