on:
  - pull_request_target

jobs:
  printenv:
    runs-on: ubuntu-22.04
    steps:
      - run: printenv
      - run: echo "$TO_ECHO"
        env:
          TO_ECHO: ${{ toJSON(github) }}
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - run: git diff --name-only ${{ github.base_ref }}..
      - run: git cat-file blob ${{ github.base_ref }}:README.md
      - run: git cat-file blob HEAD:README.md
