on:
  - pull_request_target

jobs:
  printenv:
    runs-on: ubuntu-22.04
    steps:
      - run: printenv
      - run: echo "$TO_ECHO"
        env:
          TO_ECHO: ${{ toJSON(github) }}

      - name: Checkout the base branch for the pull request.
        uses: actions/checkout@v3

      - name: Checkout the merge branch for the pull request.
        run: |-
          git fetch refs/pull/${{ github.event.pull_request.number }}/merge
          git checkout FETCH_HEAD
        shell: bash

      - run: git diff --name-only ${{ github.base_ref }}..
      - run: git cat-file blob ${{ github.base_ref }}:README.md
      - run: git cat-file blob HEAD:README.md
