name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  get_release_information:
    if: github.repository == 'jack1142/Issue2527TestRepo'
    outputs:
      tag_name: 1.2.3
      release_version: 1.2.3
    runs-on: ubuntu-latest
    steps:
      - name: Get release information
        run: |
          echo 'Getting release information...'
      - name: Show release information
        run: |
          echo 'Release information:'
          echo "- Tag name: $TAG_NAME"
          echo "- Release version: $RELEASE_VERSION"

  show_release_information:
    needs: get_release_information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Tag name: ${{ needs.get_release_information.outputs.tag_name }}'
          - name: 'Release version: ${{ needs.get_release_information.outputs.release_version }}'
    name: 'Please verify release information below:'
    steps:
      - name: Placeholder
        run: echo Placeholder

  show_release_information_tag_name:
    needs: get_release_information
    runs-on: ubuntu-latest
    name: 'Tag name: ${{ needs.get_release_information.outputs.tag_name }}'
    steps:
      - name: Placeholder
        run: echo Placeholder

  show_release_information_release_version:
    needs: get_release_information
    runs-on: ubuntu-latest
    name: 'Release version: ${{ needs.get_release_information.outputs.release_version }}'
    steps:
      - name: Placeholder
        run: echo Placeholder

  release_to_pypi:
    needs:
      - show_release_information
      - show_release_information_tag_name
      - show_release_information_release_version
    environment: Release env
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
