name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  release_information:
    if: github.repository == 'jack1142/Issue2527TestRepo'
    name: 'GO HERE BEFORE APPROVING'
    outputs:
      tag_name: 1.2.3
      release_version: 1.2.3
    runs-on: ubuntu-latest
    steps:
      - name: Get release information
        run: |
          echo 'Getting release information...'
      - name: REVIEW OUTPUT OF THIS STEP BEFORE APPROVING
        env:
          TAG_BASE_BRANCH: ${{ github.event.base_ref }}
          TAG_NAME: ${{ needs.get_release_information.outputs.tag_name }}
          RELEASE_VERSION: '1.2.3'
        run: |
          echo 'Release information:'
          echo "- Branch the tag was based off: $TAG_BASE_BRANCH"
          echo "- Tag name: ${TAG_NAME#'refs/tags/'}"
          echo "- Release version: $RELEASE_VERSION"

  release_to_pypi:
    needs: release_information
    environment: Release env
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
