name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  get_release_information:
    if: github.repository == 'jack1142/Issue2527TestRepo'
    outputs:
      tag_name: 1.2.3
      release_version: 1.2.3
    runs-on: ubuntu-latest
    steps:
      - name: Get release information
        run: |
          echo 'Getting release information...'
      - name: Output to markdown
        env:
          TAG_NAME: ${{ needs.get_release_information.outputs.tag_name }}
          RELEASE_VERSION: ${{ needs.get_release_information.outputs.release_version }}
        run: |
          echo 'Release information:' > output.md
          echo "- Tag name: $TAG_NAME" > output.md
          echo "- Release version: $RELEASE_VERSION" > output.md
      - name: Upload release information
        uses: actions/upload-artifact@v2
        with:
          name: Release information.md
          path: output.md

  Release_information:
    needs: get_release_information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Tag name: ${{ needs.get_release_information.outputs.tag_name }}'
          - name: 'Release version: ${{ needs.get_release_information.outputs.release_version }}'
    name: ${{ matrix.name }}
    steps:
      - name: Placeholder
        run: echo Placeholder

  release_to_pypi:
    needs: Release_information
    environment: Release env
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
