name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  release_to_pypi:
    if: github.repository == 'jack1142/Issue2527TestRepo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: V3/develop
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and publish
        run: |
          echo "Everything's fine..."
