name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  release_to_pypi:
    environment: Release env
    if: github.repository == 'jack1142/Issue2527TestRepo'
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context)
